
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'web-shop-monitor'
# remote_write:
#     - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
#       basic_auth:
#         username: '327560'
#         password: eyJrIjoiMzZjZDE4MzQwZGI5ODMwM2IxNDI1ODdlOGVhMWZiY2Q4OGYwODRjNyIsIm4iOiJsb2NhbF90ZXN0ZSIsImlkIjo1OTY3ODJ9

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'web-shop'
    scrape_interval: 5s

    static_configs:
      - targets: ['web-shop:6666']
        labels:
          group: 'shop'
          service: 'web-shop'

  - job_name: 'shopping-cart'
    scrape_interval: 5s

    static_configs:
      - targets: ['shopping-cart:5555']
        labels:
          group: 'shop'
          service: 'shopping-cart'

  - job_name: 'products'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['products:8080']
        labels:
          group: 'shop'
          service: 'products'

  - job_name: 'span-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['agent:1234']
        labels:
          group: 'shop'


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://web-shop:6666/cart
        - http://web-shop:6666/shop
        - http://products:8080
        - http://shopping-cart:5555/cart/blackbox
        - https://example.com
        - https://www.telegraph.co.uk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115