server:
  log_level: debug

logs:
  configs:
  - name: loki
    clients:
      - url: https://162750:eyJrIjoiNjJmYjIzZjYzOTFlYjcyYjgyOWNiNjcwZDgxNTZlODQ2MjgzZDU0ZCIsIm4iOiJsb2NhbF90ZXN0ZV9sb2ciLCJpZCI6NTk2NzgyfQ==@logs-prod3.grafana.net/loki/api/v1/push
        external_labels:
          job: agent
  positions_directory: /tmp/positions

traces:
  configs:
  - name: latencyEndpoint
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    remote_write:
      - endpoint: tempo-us-central1.grafana.net:443
        basic_auth:
          username: 159258
          password: eyJrIjoiN2JkNDE0NTZhMzg4MWQ5OGZkZTRkNjUwNjRkOTM4ZGZmODUwNWRiMSIsIm4iOiJsb2NhbF90ZXN0ZV90cmFjZSIsImlkIjo1OTY3ODJ9
    spanmetrics:
      dimensions:
        - name: http.method
        - name: http.target
        - name: team.name
      handler_endpoint: 0.0.0.0:1234
    automatic_logging:
      backend: logs_instance
      logs_instance_name: loki
      roots: true
      processes: true
      spans: true
      span_attributes:
        - http.method
        - http.target
        - http.status_code
      overrides:
        trace_id_key: "traceID"

